server:
  port: 18082

spring:
  application:
    name: spring-boot-service3
  cloud:
    consul:
      host: 47.108.202.112
      port: 8500
      discovery:
        service-name: service2 #模拟和 spring-boot-service2进行负责均衡部署
        heartbeat:
          enabled: true #打开心跳检测
  zipkin:
    base-url: http://localhost:9411 #zipkin server 地址
  sleuth:
    sampler:
      probability: 1.0 # 取样率，本地环境可以1.0 ，默认为0.1 = 10%
